### ISSUE TITLE
Change SEM to 95% CI

### ISSUE THREAD

**Issue by rbcavanaugh** [aphasia-apps/pnt#2]
Meeting issue #1: WH and GF suggest indicating 95% CI instead of SEM. 

95% CI  = ability +/- 1.96 * SEM. 

- add to downloaded files
- change results plot
- change results text

Question: do we want the stopping criterion to also be based on a 95% CI?

**Comment by rbcavanaugh** [comment]
I have done this in the code. The user now selects a desired 95% CI instead of SEM. The app converts the 95% CI to SEM, then does its thing. converts back to 95% ci at the end. 

I need some help getting from ability, SEM -> ability, SD for plot making though...

**Comment by william-hula** [comment]
Here's a feature suggestion that I'd appreciate the team's input on: Permit the user to specify the confidence level of the credible interval? Make 95% the default but let people choose any value, maybe >= 69% (about .5SD) or 84% (1SD)? Also, I'm can probably help with 'getting from ability, SEM -> ability, SD for plot making', but we might need to talk about; I'm not sure I understand exactly what you're asking..

**Comment by william-hula** [comment]
A 2-tailed 95% CI of 8 implies an SEM of 8/1.96 = 4.08, where 1.96 is the value of the standard normal distribution associated with the 97.5th percentile. You'd take the score estimate +/- 4.08&1.96 to get the CI. Is that what you asking?

to find the value of the standard normal by which you multiply the SEM: qnorm(p = 1 - (1 - alpha)/2), where alpha is the desired confidence level expressed as a proportion. So, if someone selects variable length and specifies the stopping rule as 95%CI < 8, the test would run until the SEM is < 4.08, or equivalently until the test information is > 1 / 4.08 ^ 2, because information is the inverse of the error variance which is the SEM squared..

**Comment by rbcavanaugh** [comment]
yup - this is helpful thank you. 

So what would a reasonable range of 95% CI width's be to ask for? Something like 2 to 8 iterated by 1? (2, 3, 4, 5, 6, 7, 8)

**Comment by william-hula** [comment]
Well, the range of SEMs for the full test in the current calibration sample is 1.03 to 3.35, for 95% CI widths ranging from 4.04 to 13.1.  And CAT will make those larger. Do you think it might be better to let users specify the desired SEM rather than 95%CI?

**Comment by william-hula** [comment]
Yeah, I hear you on CIs vs SEM. Let me run some cat simulations with the T-scaled parameters to generate the range of plausible values. Another strategy would be to go to our recent pubs, get the SEs from there, then reduce them by a factor of 1.4,  to reflect that the SD of the sample in that work was about 1.4 but with the Bayesian reestimation the SD is effectively scaled to unit size (as in = 1), then multiply that number by 10 to reflect the T-score transform. That''ll give you a ballpark on the SEMs and you can get 95% CI widths by multiply by 2 x 1.96 from there.

On the question of 95% Cis for different use cases, I usually think of that in terms of different confidence levels, e.g., a 90% or 80% CI for low-stakes individual cases, 95% for higher stakes stuff.

From: Rob Cavanaugh ***@***.***>
Sent: Wednesday, October 6, 2021 11:18 PM
To: aphasia-apps/pnt ***@***.***>
Cc: Hula, William D ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [aphasia-apps/pnt] Change SEM to 95% CI (#2)


No I think the CI will be more familiar to users - that is probably better. I'm just not that familiar with what range of 95% CIs to expect on a t-scale, or for this test in particular or how precise I might want to 95% width for different use-cases. Assuming some users might have similar questions, it might just be a matter of providing a little more information about the variable length version of the test.

-
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Faphasia-apps%2Fpnt%2Fissues%2F2%23issuecomment-937410366&data=04%7C01%7C%7Cf94b77bcc6fc4fe399a908d9894102b8%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637691734597322589%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=J5Ih17B%2FJHK5LK0fvex8wBeFWsK3YKKiJgMBSpzkGPc%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAU44R7AYVGIHHLYEI26KDZDUFUGMPANCNFSM475G7YOA&data=04%7C01%7C%7Cf94b77bcc6fc4fe399a908d9894102b8%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637691734597332547%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=XtR9kDp2fsv7SCmPHgGaZcQXFpr%2B4mE9JPKnKRsD8s4%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7Cf94b77bcc6fc4fe399a908d9894102b8%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637691734597332547%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=BpHaj4s%2Fq29q4B4E8oMErI74vdU7fe1sEAK0UtGIItU%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7Cf94b77bcc6fc4fe399a908d9894102b8%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637691734597342506%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=5M3xsaWbDUF%2BTWYusaHOer3obA4JzZs%2FHJSdQfg059c%3D&reserved=0>.

**Comment by william-hula** [comment]
Rob (and everybody else)
I wonder if instead of CI widths we should let users define the variable-length stopping rule in terms of marginal reliability? Below is some code that lays out the relationships between SEM, confidence level, CI wiidth, and the marginal reliability coefficient. It takes the score estimate, SEM and desired confidence level as input, and returns the upper and lower CI bounds, the CI width, and the marginal reliability coefficient.


theta <- 50
sem <- 5
conf_level <- 0.95
std_nml_deviate <-qnorm(p = 1-(1 - conf_level)/2, mean = 0, sd = 1)

ci_lb <- signif(theta - sem*std_nml_deviate, digits = 3) 
ci_ub <- signif(theta + sem*std_nml_deviate, digits = 3)

ci_width <- ci_ub - ci_lb

# because we know the total population variance on this scale is 10^2 = 100,
# and total variance is equal to true latent trait variance plus error variance,
# and reliability is the ratio of true score variance to total variance, we can 
# derive a marginal reliability coefficient for any given score thusly:
rel <- 1 - sem^2/100

**Comment by rbcavanaugh** [comment]
Will - this seems pretty trivial from a coding standpoint. I am not very familiar with marginal reliability in the IRT context - what is the interpretation of the marginal reliability coefficient? Similar to parallel forms reliability?

**Comment by rbcavanaugh** [comment]
ok thanks - I will work on incorporating this afternoon. 

Will - can you write a quick blurb for users about the marginal reliability coefficient and the rationale for where to set it?

**Comment by rbcavanaugh** [comment]
closing this as it is largely taken care of. we did not implement marginal reliability.
